site_name: ai-job-assist
repo_url: https://github.com/wp225/ai-job-assist
site_url: https://wp225.github.io/ai-job-assist
site_description: Job Assist with AI. Scrape, Rank, Apply with custom Resume all with agents
site_author: Jeorge
repo_name: wp225/ai-job-assist
edit_uri: edit/main/docs/
copyright: Maintained by <a href="https://github.com/wp225">Jeorge</a>.
nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - License: license.md
theme:
  name: material
  palette:
    scheme: slate
    primary: deep purple
    accent: purple
  icon:
    repo: fontawesome/brands/github
plugins:
  - search
  - gh-admonitions
  - minify:
      minify_html: true
      htmlmin_opts:
        remove_comments: true
markdown_extensions:
  - pymdownx.superfences
  - pymdownx.highlight:
      use_pygments: true
      pygments_style: material
      noclasses: true
  - pymdownx.inlinehilite
  - pymdownx.emoji
  - admonition
